<?php

namespace Acme\ReactorApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function findAllByUserId($id)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT ms
                FROM AcmeReactorApiBundle:Message ms
                WHERE ms.to_user = :id
                  OR ms.from_user = :id
                ORDER BY ms.created_at DESC'
            )->setParameter('id', $id)->getArrayResult();
    }
}
