<?php

namespace Acme\ReactorApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getFriends($id)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT u.id, u.username, u.phone
                FROM AcmeReactorApiBundle:User u
                LEFT JOIN u.friends fr
                WHERE fr.user_id = :id'
            )->setParameter('id', $id)->getArrayResult();
    }

    public function findByUserName($username)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT u.id, u.username, u.phone
                FROM AcmeReactorApiBundle:User u
                WHERE u.username LIKE :username'
            )->setParameter('username', '%'.$username.'%')->getArrayResult();
    }

    public function findUserByPhone($phone)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT u.id, u.username
                FROM AcmeReactorApiBundle:User u
                WHERE u.phone = :phone'
            )->setParameter('phone', $phone)->getArrayResult();
    }

    public function findByUsernameAndEmail($username, $email)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT u.username, u.email
                FROM AcmeReactorApiBundle:User u
                WHERE u.username = :username
                  OR u.email = :email'
            )->setParameters(array('username' => $username, 'email' => $email))->getArrayResult();
    }
    public function findAllUsersInDateFromTo($from, $to, $first, $max)
    {
        $users = $this->getEntityManager()
            ->createQuery('
                SELECT u
                FROM AcmeReactorApiBundle:User u
                WHERE u.created_at >= :from AND u.created_at <= :to'
            )
            ->setParameters(array('from' => $from, 'to' => $to));
        $count = Paginate::getTotalQueryResults($users); // Step 1
        $paginateQuery = Paginate::getPaginateQuery($users, $first, $max); // Step 2 and 3
        $result = $paginateQuery->getResult();
        return $result;
    }

    public function findAllUsersInDate($from, $to)
    {
        $users = $this->getEntityManager()
            ->createQuery('
                SELECT u
                FROM AcmeReactorApiBundle:User u
                WHERE u.created_at >= :from AND u.created_at <= :to'
            )
            ->setParameters(array('from' => $from, 'to' => $to))
            ->getResult();
        return $users;
    }
}
