Acme\ReactorApiBundle\Entity\Message:
  type: entity
  repositoryClass: Acme\ReactorApiBundle\Repository\MessageRepository
  table: message
  id:
    id:
      type: bigint
      generator: { strategy: AUTO }
  fields:
    from_user:
      type: integer
    to_user:
      type: integer
    text:
      type: text
      nullable: true
    photo:
      type: string
      lenght: 255
    reaction_photo:
      type: string
      lenght: 255
      nullable: true
    is_read:
      type: boolean
      nullable: true
    created_at:
      type: datetime
    deletedByTo:
      type: integer
    deletedByFrom:
      type: integer

  manyToOne:
      to:
        targetEntity: User
        inversedBy: toUser
        joinColumn:
          name: to_user
          referencedColumnName: id
      from:
        targetEntity: User
        inversedBy: fromUser
        joinColumn:
          name: from_user
          referencedColumnName: id
