Acme\ReactorApiBundle\Entity\User:
  type: entity
  repositoryClass: Acme\ReactorApiBundle\Repository\UserRepository
  table: user
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 255
      unique: true
    email:
      type: string
      length: 255
      unique: true
    password:
      type: string
      length: 255
    phone:
      type: bigint
      length: 12
    device_token:
      type: string
      length: 256
      nullable: true
    session_hash:
      type: string
      length: 255
      nullable: true
    privacy_message:
      type: boolean
      generator: { strategy: 1 }
    created_at:
      type: datetime
      nullable: true
  oneToMany:
    friends:
      targetEntity: Friend
      mappedBy: user
    toUser:
      targetEntity: Message
      mappedBy: to
    fromUser:
      targetEntity: Message
      mappedBy: from
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
