Acme\ReactorApiBundle\Entity\User:
  type: entity
  repositoryClass: Acme\ReactorApiBundle\Repository\UserRepository
  table: user
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 255
    email:
      type: string
      length: 255
      unique: true
    password:
      type: string
      length: 255
    phone:
      type: integer
      lenghth: 12
    device_token:
      type: string
      length: 256
      nullable: true
    session_hash:
      type: string
      lenghth: 255
      nullable: true
    created_at:
      type: datetime
      nullable: true
  oneToMany:
    friends:
      targetEntity: Friend
      mappedBy: user
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
