# MyBundle/Resources/config/admin.yml

services:
    sonata.admin.tag:
        class: Acme\ReactorApiBundle\Admin\StaticInfoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: posts, label: "Static information" }
        arguments:
            - ~
            - Acme\ReactorApiBundle\Entity\StaticInfo
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AcmeReactorApiBundle]]
            
    reactr.photo.form.type:
            class: Acme\ReactorApiBundle\Form\Type\PhotoFormType
            tags:
                - { name: form.type, alias: reactr_photo_list }

    reactr.sponsor:
        class: Acme\ReactorApiBundle\Admin\SponsorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: posts, label: "Sponsors" }
        arguments:
            - ~
            - Acme\ReactorApiBundle\Entity\Sponsor
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AcmeReactorApiBundle]]