registration:
  pattern: /registration/
  defaults: { _controller: AcmeReactorApiBundle:Api:registration }
  requirements:
    _method:  POST

login:
  pattern: /login/
  defaults: { _controller: AcmeReactorApiBundle:Api:login }
  requirements:
    _method:  POST

send_message:
  pattern: /sendMessage/
  defaults: { _controller: AcmeReactorApiBundle:Api:sendMessage }

get_messages:
  pattern: /getMessages/
  defaults: { _controller: AcmeReactorApiBundle:Api:getMessages }

add_friend:
  pattern: /addFriend/
  defaults: { _controller: AcmeReactorApiBundle:Api:addFriend }

get_friends:
  pattern: /getFriends/
  defaults: { _controller: AcmeReactorApiBundle:Api:getFriends }

get_friends_who_add_me:
  pattern: /getWhoAddMe/
  defaults: { _controller: AcmeReactorApiBundle:Api:getWhoAddMe }

search_friends:
  pattern: /searchFriends/
  defaults: { _controller: AcmeReactorApiBundle:Api:searchFriends }

delete_friend:
  pattern: /deleteFriends/
  defaults: { _controller: AcmeReactorApiBundle:Api:deleteFriends }

check_user_in_system:
  pattern: /checkUserInSystem/
  defaults: { _controller: AcmeReactorApiBundle:Api:checkUserInSystem }

get_static_info:
  pattern: /getStaticInfo/
  defaults: { _controller: AcmeReactorApiBundle:Api:getStaticInfo }
