registration:
  pattern: /registration/
  defaults: { _controller: AcmeReactorApiBundle:Api:registration }
  requirements:
    _method:  POST

login:
  pattern: /login/
  defaults: { _controller: AcmeReactorApiBundle:Api:login }
  requirements:
    _method:  POST

set_privacy_message:
  pattern: /setPrivacyMessage/
  defaults: { _controller: AcmeReactorApiBundle:Api:setPrivacyMessage }

edit_user_data:
  pattern: /editUserData/
  defaults: { _controller: AcmeReactorApiBundle:Api:editUserData }

send_messages:
  pattern: /sendMessages/
  defaults: { _controller: AcmeReactorApiBundle:Api:sendMessages }

countIsNotRead:
  pattern: /countNotReadMessage/
  defaults: { _controller: AcmeReactorApiBundle:Api:countNotReadMessage }

get_messages:
  pattern: /getMessages/
  defaults: { _controller: AcmeReactorApiBundle:Api:getMessages }

read_messages:
  pattern: /readMessages/
  defaults: { _controller: AcmeReactorApiBundle:Api:readMessages }

add_friend:
  pattern: /addFriend/
  defaults: { _controller: AcmeReactorApiBundle:Api:addFriend }

get_friends:
  pattern: /getFriends/
  defaults: { _controller: AcmeReactorApiBundle:Api:getFriends }

get_friends_who_add_me:
  pattern: /getWhoAddMe/
  defaults: { _controller: AcmeReactorApiBundle:Api:getWhoAddMe }

search_friends:
  pattern: /searchFriends/
  defaults: { _controller: AcmeReactorApiBundle:Api:searchFriends }

block_friend:
  pattern: /blockFriend/
  defaults: { _controller: AcmeReactorApiBundle:Api:setBlockFriend }

delete_friend:
  pattern: /deleteFriend/
  defaults: { _controller: AcmeReactorApiBundle:Api:deleteFriend }

check_user_in_system:
  pattern: /checkUserInSystem/
  defaults: { _controller: AcmeReactorApiBundle:Api:checkUserInSystem }

get_static_info:
  pattern: /getStaticInfo/
  defaults: { _controller: AcmeReactorApiBundle:Api:getStaticInfo }

check_username_and_email:
  pattern: /checkUsernameAndEmail/
  defaults: { _controller: AcmeReactorApiBundle:Api:checkUsernameAndEmail }

delete_message:
  pattern: /deleteMessage/
  defaults: { _controller: AcmeReactorApiBundle:Api:deleteMessage }

all_photo_list:
     pattern:      /admin/acme/reactorapi/photo/list/{page}
     defaults:     { _controller: AcmeReactorApiBundle:PhotoAdmin:photoList, page:1 }

xml_table:
     pattern:      /admin/acme/reactorapi/dowload/xml/{string}
     defaults:     { _controller: AcmeReactorApiBundle:PhotoAdmin:getXmlTable, data: 1 }

remind_password:
  pattern: /remindPassword/
  defaults: { _controller: AcmeReactorApiBundle:Api:remindPassword }

reset_password:
  pattern: /resetPassword/
  defaults: { _controller: AcmeReactorApiBundle:Api:resetPassword }

get_sponsor:
  pattern: /getSponsor/
  defaults: { _controller: AcmeReactorApiBundle:Api:getSponsor }

sponsor_logo:
     pattern:      /acme/reactorapi/sponsor/change/{id}
     defaults:     { _controller: AcmeReactorApiBundle:SponsorAdmin:change }

new_sponsor:
     pattern:      /acme/reactorapi/sponsor/add
     defaults:     { _controller: AcmeReactorApiBundle:SponsorAdmin:addNewSponsor }