Acme\ReactorApiBundle\Entity\User:
  constraints:
          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ username ]
              errorPath: username
              message: This user exist in system
          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ email ]
              errorPath: email
              message: This email exist in system
          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ phone ]
              errorPath: phone
              message: This phone exist in system
  properties:
          username:
              - NotBlank: ~
          email:
              - Email: ~
          phone:
              - NotBlank: ~
#  constraints:
#          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
