Acme\ReactorApiBundle\Entity\User:
  constraints:
          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ username ]
              errorPath: username
              message: This user exist in system
          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ email ]
              errorPath: email
              message: This email exist in system
          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ phone ]
              errorPath: phone
              message: This phone exist in system
  properties:
          username:
              - NotBlank: ~
          email:
              - Email: ~
          phone:
              - NotBlank: ~
              - Length:
                  min: 5
                  max: 20
                  minMessage: Phone number is too short
                  maxMessage: Phone number is too long
              #- Range:
              #    min: 1
              #    max: 9999999999
              #    minMessage: Phone number is too short
              #    maxMessage: Phone number is too long
              #    invalidMessage: Phone number must be in numeric format
#  constraints:
#          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
